name: Generate Document

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Document version required'
        required: false
        default: ""
  push:
    branches: 
      - master
    paths: 
      - '**.py'
      - '**.pyi'
        
    

jobs:
  docs:
    name: Generate API References
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Setup Python
      uses: actions/setup-python@v2

    - name: Prepare sphinx environment
      run: |
        pip install pip -U
        pip install -e .
        pip install git+https://github.com/nonebot/sphinx-markdown-builder
        pip install sphinx
    
    - name: Generate document struct
      working-directory: docs/script
      env:
        RELEASE_VER: ${{ github.event.inputs.version }}
      run: |
        if [ -z "RELEASE_VER" ]; then export RELEASE_VER=$GITHUB_SHA ; fi
        echo ":warning: Not implemented yet ($RELEASE_VER) "

